from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


def make_pdf(path="backend/data/knowledge.pdf"):
    c = canvas.Canvas(path, pagesize=letter)
    text = c.beginText(40, 750)

    lines = [
    "Windows Command Prompt (CMD) Knowledge Base",
    "",
    "Q: How do I list all files and folders in the current directory?",
    "A: Use 'dir'. To see hidden files, use 'dir /a'.",
    "",
    "Q: How do I change the current directory?",
    "A: Use 'cd [folder_name]'. To go back one level, use 'cd ..'.",
    "",
    "Q: How do I clear the command prompt screen?",
    "A: Type 'cls' and press Enter.",
    "",
    "Q: How do I create a new folder?",
    "A: Use 'mkdir [folder_name]' or 'md [folder_name]'.",
    "",
    "Q: How do I delete a specific file?",
    "A: Use 'del [filename]'. Be careful, as this does not move items to the Recycle Bin.",
    "",
    "Q: How do I delete an empty folder?",
    "A: Use 'rmdir [folder_name]' or 'rd [folder_name]'.",
    "",
    "Q: How do I delete a folder and all its contents?",
    "A: Use 'rmdir /s [folder_name]'. You will be asked to confirm.",
    "",
    "Q: How do I copy a file to another location?",
    "A: Use 'copy [source_file] [destination_folder]'.",
    "",
    "Q: How do I move a file to another location?",
    "A: Use 'move [source_file] [destination_folder]'.",
    "",
    "Q: How do I rename a file?",
    "A: Use 'ren [old_name] [new_name]'.",
    "",
    "Q: How do I view the contents of a text file directly in the terminal?",
    "A: Use 'type [filename.txt]'.",
    "",
    "Q: How do I check my IP address configuration?",
    "A: Use 'ipconfig'. For detailed info, use 'ipconfig /all'.",
    "",
    "Q: How do I test connectivity to a website or IP address?",
    "A: Use 'ping [website_or_IP]'. Example: 'ping google.com'.",
    "",
    "Q: How do I trace the route data takes to reach a destination?",
    "A: Use 'tracert [website_or_IP]'.",
    "",
    "Q: How do I display active network connections and ports?",
    "A: Use 'netstat -a' to see all active connections.",
    "",
    "Q: How do I check if a specific website is reachable via DNS?",
    "A: Use 'nslookup [domain_name]'.",
    "",
    "Q: How do I flush the DNS resolver cache?",
    "A: Use 'ipconfig /flushdns'. Useful for fixing connection issues.",
    "",
    "Q: How do I release and renew my IP address?",
    "A: First type 'ipconfig /release', then type 'ipconfig /renew'.",
    "",
    "Q: How do I view a list of currently running tasks/processes?",
    "A: Use 'tasklist'.",
    "",
    "Q: How do I force stop a running process?",
    "A: Use 'taskkill /IM [process_name] /F'. Example: 'taskkill /IM notepad.exe /F'.",
    "",
    "Q: How do I view detailed system configuration information?",
    "A: Use 'systeminfo'. It shows OS version, memory, boot time, and more.",
    "",
    "Q: How do I check the Windows version?",
    "A: Type 'ver' to see the simple version number.",
    "",
    "Q: How do I scan system files for corruption?",
    "A: Use 'sfc /scannow'. You must run CMD as Administrator.",
    "",
    "Q: How do I check the hard drive for errors?",
    "A: Use 'chkdsk [drive_letter]:'. To fix errors, use 'chkdsk /f'.",
    "",
    "Q: How do I format a disk drive?",
    "A: Use 'format [drive_letter]:'. Warning: This erases all data on the drive.",
    "",
    "Q: How do I manage disk partitions?",
    "A: Type 'diskpart' to enter the disk partition utility tool.",
    "",
    "Q: How do I shutdown the computer immediately?",
    "A: Use 'shutdown /s /t 0'.",
    "",
    "Q: How do I restart the computer?",
    "A: Use 'shutdown /r /t 0'.",
    "",
    "Q: How do I abort a scheduled shutdown?",
    "A: Use 'shutdown /a'.",
    "",
    "Q: How do I copy files including subdirectories (Robust Copy)?",
    "A: Use 'robocopy [source] [destination] /E'. It is faster and more reliable than xcopy.",
    "",
    "Q: How do I view the folder structure graphically?",
    "A: Use 'tree'. To see files inside folders as well, use 'tree /f'.",
    "",
    "Q: How do I change a user's password?",
    "A: Use 'net user [username] [new_password]'. Requires Admin privileges.",
    "",
    "Q: How do I add a new user account?",
    "A: Use 'net user [username] [password] /add'.",
    "",
    "Q: How do I view file attributes (hidden, read-only, etc.)?",
    "A: Use 'attrib'. To make a file hidden, use 'attrib +h [filename]'.",
    "",
    "Q: How do I see the command history?",
    "A: Use 'doskey /history' to see commands you typed in the current session.",
    "",
    "Q: How do I get the MAC address of my network adapters?",
    "A: Use 'getmac'.",
    "",
    "Q: How do I update Group Policy settings manually?",
    "A: Use 'gpupdate /force'.",
    "",
    "Q: How do I list installed drivers?",
    "A: Use 'driverquery'.",
    "",
    "Q: How do I check file associations?",
    "A: Use 'assoc'. To see what opens .txt files, type 'assoc .txt'.",
    "",
    "Q: How do I schedule a command to run later?",
    "A: Use 'schtasks'. This replaces the older 'at' command.",
    "",
    "Q: How do I see help documentation for a specific command?",
    "A: Type '[command] /?' or 'help [command]'.",
    "",
    "Q: How do I output text to the screen or a file?",
    "A: Use 'echo [text]'. To write to a file: 'echo [text] > [filename.txt]'.",
    "",
    "Q: How do I open the Registry Editor from CMD?",
    "A: Type 'regedit' and press Enter."
    ]

    for line in lines:
        text.textLine(line)

    c.drawText(text)
    c.showPage()
    c.save()


if __name__ == "__main__":
    make_pdf()